LOG:
  LOG_DIR: ${LOG_DIR}

QDRANT:
  URL: ${QDRANT_URL}
  API_KEY: ${QDRANT_API_KEY}
  COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
  DENSE_VECTOR_SIZE: ${QDRANT_DENSE_VECTOR_SIZE}

EMBEDDING:
  DENSE_MODEL: ${EMBEDDING_DENSE_MODEL}
  SPARSE_MODEL: ${EMBEDDING_SPARSE_MODEL}

RETRIEVAL:
  TOP_K: ${RETRIEVAL_TOP_K}
  KEYWORD_THRESHOLD: ${RETRIEVAL_KEYWORD_THRESHOLD}

