LOG:
  LOG_DIR: ${LOG_DIR}

QDRANT:
  URL: ${QDRANT_URL}
  API_KEY: ${QDRANT_API_KEY}
  COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
  DENSE_VECTOR_SIZE: ${QDRANT_DENSE_VECTOR_SIZE}

EMBEDDING:
  API_KEY: ${EMBEDDING_API_KEY}
  EMBEDDING_BASE_URL: ${EMBEDDING_BASE_URL}
  EMBEDDING_DIMENSIONS: ${EMBEDDING_DIMENSIONS} 
  EMBEDDING_MODEL: ${EMBEDDING_MODEL}

PIPELINE:
  CHUNK_SIZE: 1200
  CHUNK_OVERLAP: 150
  MINIMUM_CHUNK_SIZE: 250

RETRIEVAL:
  TOP_K: ${RETRIEVAL_TOP_K}
  KEYWORD_THRESHOLD: ${RETRIEVAL_KEYWORD_THRESHOLD}

